name: Github Pages
on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: 0 0 1 * *
      
jobs:
  Deploy-Pages:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Deps
        run: yarn add -D monaco-editor monaco-editor-webpack-plugin

      - name: Build App
        run: yarn build

      - name: Prepare Statics
        run: cp -r samples build && rm -r docs && cp -r build docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
